const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
const FORM_SUBMIT_VALUE = 'FORM_SUBMIT_VALUE';
const FORM_RESET = 'FORM_RESET';

module.exports = { BEGIN_AJAX_CALL, AJAX_CALL_ERROR, FORM_SUBMIT_VALUE, FORM_RESET };
